### ISSUE TITLE
Can you explain your PID tuning a little?

### ISSUE THREAD

**Issue by CamSoper** [DBorello/PiSmoker#2]
Hi there! I'm re-imagining your work a little bit for [my own project](https://github.com/CamSoper/Inferno). 

Can you please explain [that 0.5 on the P term](https://github.com/DBorello/PiSmoker/blob/e0279053a8283f6599f332823556935a4f9139d6/PID.py#L42) a bit more? On your blog, you said, "This centers the control at 0.5 if there is no errors."  I'm having a hard time conceptualizing what you mean by this and I'm hoping you can explain it for me.

**Comment by DBorello** [comment]
Hi Cam,

Best of luck on your project.  The schematic certainly looks familiar!

Short answer to your questions, probably not :)  I haven't really messed
with it in 5 years.  Furthermore, the blog post was written after I broke
my leg, so there may be some Opiods in play.

In any case, I think the 0.5 is there to give us a starting place for the
control.  If we had no error, and only proportional control, we would want
to return the value that would keep constant temperature.  0 and 1
obviously aren't right, so 0.5 was randomly chosen.  However, when we add
the integral control back in, it should provide a constant offset to
correct the 0.5.

I hope this helps!  Please keep me posted as your project progresses.

Sincerely,
Dan

**Comment by CamSoper** [comment]
Thanks for the quick reply! 

The only other thing your PID algorithm does that's a little different from most I've seen is the [integral is getting capped at half Ki](https://github.com/DBorello/PiSmoker/blob/e0279053a8283f6599f332823556935a4f9139d6/PID.py#L26). Do you have any recollection of why you did this?

I want to thank you for doing the trailblazing on this project! My Traeger Junior Elite had wild temperature swings with the factory controller, and your project really inspired me. Since I work on .NET Core at Microsoft, I wanted to do things the .NET Core way, hence the re-imagining. 🙂  This is definitely going into a conference talk at some point and I'll be sure to give you all the credit on the math. 😆 

If you're interested, my [hardware project pics are here](https://1drv.ms/u/s!Ag9fVAifJI6dsrwlhf-iGDwD4qkaxw?e=dpgySN) and I've done a fair amount of [tweeting](https://twitter.com/camsoper) as I've worked on this over the past month.

Thank you again!

**Comment by DBorello** [comment]
Hi Cam,

I love it!  Excellent project.  I see you are doing a better job
documenting it than I did :-)

The integral term is capped to avoid it taking over.  During startup, the
error could get pretty big.  To be honest, I don't remember how I came up
with the cap.

Best of luck!

Sincerely,
Dan

**Comment by CamSoper** [comment]
Thank you again, Dan!
